spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/gametime
spring.datasource.username=postgres
spring.datasource.password=turner
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=true
spring.data.jpa.repositories.bootstrap-mode=default
spring.jpa.properties.hibernate.default_schema=gametime
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog.yml
